config/routes.rb
CoinAuction::Application.routes.draw do |map|
  match "home" => 'home#index', :as => :home
  match "home/all_announcements" => 'home#all_announcements', :as => :all_announcements
  match "home/:id" => "home#announcement", :as => :announcement
  
  get "account/show"
  get "account/bids"
  get "account/history"
  match "logout" => 'user_sessions#destroy'
  resource :user_session, :only => [:destroy, :create, :new]

  scope :module => "auction" do
    match "auctions/categories" => 'customer_auctions#categories', :as => :auctions_categories
    match "auctions/list" => 'customer_auctions#list', :as => :auctions_list
    match "auctions/view/:id" => 'customer_auctions#view', :as => :auctions_view
    resource :customer_bid, :only => [:new, :create, :destroy]
  end

  
  namespace "admin" do
    get "home/index"
    resources :auctions do
      delete :destroy_bid, :on => :member
    end
    resources :items
    resources :announcements
    resources :users
  end

  

  root :to => 'home#index'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_filter :require_user
  
  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @announcements = Announcement.recent_10
  end

  def announcement
    @announcement = Announcement.find(params[:id])
  end

  def all_announcements
    @announcements = Announcement.recent_first
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/all_announcements.html.erb
<h2>Announcements</h2>

<% @announcements.each do |announcement| %>
  <%= render 'admin/announcements/announcement', :locals => {:announcement => announcement} %>
  <%= link_to "Read More", announcement_path(announcement.id) %>
<% end %>
<%= link_to "Home", home_path %>

app/views/home/announcement.html.erb
<%= render 'admin/announcements/announcement'  %>
<%= link_to "Home", home_path %>

app/views/home/index.html.erb
<h2>Recent Announcements</h2>

<% @announcements.each do |announcement| %>
  <%= render 'admin/announcements/announcement', :locals => {:announcement => announcement} %>
<%= link_to "Read More", announcement_path(announcement.id) %>
<% end %>
<%= link_to "Announcement History", all_announcements_path %>