config/routes.rb
CoinAuction::Application.routes.draw do |map|
  match "home" => 'home#index', :as => :home
  match "home/all_announcements" => 'home#all_announcements', :as => :all_announcements
  match "home/:id" => "home#announcement", :as => :announcement
  
  get "account/show"
  get "account/bids"
  get "account/history"
  match "logout" => 'user_sessions#destroy'
  resource :user_session, :only => [:destroy, :create, :new]

  scope :module => "auction" do
    match "auctions/categories" => 'customer_auctions#categories', :as => :auctions_categories
    match "auctions/list" => 'customer_auctions#list', :as => :auctions_list
    match "auctions/view/:id" => 'customer_auctions#view', :as => :auctions_view
    resource :customer_bid, :only => [:new, :create, :destroy]
  end

  
  namespace "admin" do
    get "home/index"
    resources :auctions do
      delete :destroy_bid, :on => :member
    end
    resources :items
    resources :announcements
    resources :users
  end

  

  root :to => 'home#index'

end

app/models/auction.rb
include ActionView::Helpers::NumberHelper
class Auction < ActiveRecord::Base
  has_many :bids, :dependent => :destroy
  belongs_to :item

  validates_presence_of :starting_amount, :item_id, :end_time
  validates_numericality_of :starting_amount, :greater_than_or_equal_to => 0
  validates_presence_of :current_bid, :on => :update
  validates_numericality_of :current_bid, :on => :update
  
  after_create {|auction| auction.current_bid = auction.starting_amount if auction.current_bid.blank?}

  scope :category_group, joins(:item).order("item.series desc").includes(:item)
  scope :list_by_time_left, order("end_time desc").includes(:item)
  scope :list_by_cheapest, order("current_bid asc").includes(:item)
  scope :list_by_most_expensive, order("current_bid desc").includes(:item)
  scope :list_by_name, order("name desc").includes(:item)
  scope :list_by_popularity, joins(:bids).group('auctions.id').order("count(bids.id) desc").includes(:item)


  def current_bid_to_currency
    number_to_currency(self.current_bid)
  end

  def time_left_long
    t1 = Time.parse(self.end_time.to_s)
    t2 = Time.parse(Time.now.to_s)
    tl = t1 - t2
    if tl < 0
      return "Ended"
    end
    parse_time_left_long(tl)
  end

  def time_left_short
    t1 = Time.parse(self.end_time.to_s)
    t2 = Time.parse(Time.now.to_s)
    tl = t1 - t2
    if tl < 0
      return "Ended"
    end
    parse_time_left_short(tl)
  end


  def update_highest_bid
    if self.bids > 1
      max = self.bids.maximum("amount")
      max_bid = self.bids.where("amount == ?", max)
      self.update_attributes(:current_bid => max, :top_bidder => max_bid.first.user.login)
    else
      self.update_attributes(:current_bid => self.starting_amount, :top_bidder => "")
    end
  end


  
  private

  

  def parse_time_left_long(time)
    s=""
    seconds = (time%(60)).to_i
    minutes = ((time%(60*60))/60).to_i
    hours = (time%(60*60*24)/(60*60)).to_i
    days = (time/(60*60*24)).to_i
    s << "#{days} day#{'s' if days > 1}, " if days > 0
    s << "#{hours} hr#{'s' if hours > 1}, " if hours > 0
    s << "#{minutes} min#{'s' if minutes > 1}, " if minutes > 0
    s << "#{seconds} sec" if seconds > 0
    return s
  end

  def parse_time_left_short(time)
    s="Error"
    seconds = (time%(60)).to_i
    minutes = ((time%(60*60))/60).to_i
    hours = (time%(60*60*24)/(60*60)).to_i
    days = (time/(60*60*24)).to_i
    if days > 0
      s = "#{days} day#{'s' if days > 1}, " if days > 0
      s << "#{hours} hr#{'s' if hours > 1}" if hours > 0
    else
      s = "#{hours} hr#{'s' if hours > 1}, " if hours > 0
      s << "#{minutes} min#{'s' if minutes > 1}, " if minutes > 0
      s << "#{seconds} sec" if seconds > 0
    end
    return s
  end
end


#  def time_left_long(end_datetime, current_datetime=Time.now)
#    t1 = Time.parse(end_datetime.to_s)
#    t2 = Time.parse(current_datetime.to_s)
#    tl = t1 - t2
#    if tl < 0
#      return "Ended"
#    end
#    parse_time_left_long(tl)
#  end

app/controllers/admin/auctions_controller.rb
class Admin::AuctionsController < ApplicationController
  before_filter :require_user
  
  # GET /auctions
  # GET /auctions.xml
  def index
    @auctions = Auction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @auctions }
    end
  end

  # GET /auctions/1
  # GET /auctions/1.xml
  def show
    @auction = Auction.find(params[:id])
    @item = @auction.item
    @bids = @auction.bids.order("created_at desc")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @auction }
    end
  end

  # GET /auctions/new
  # GET /auctions/new.xml
  def new
    @auction = Auction.new
    @auction.item_id = params[:item_id] if params[:item_id]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @auction }
    end
  end

  # GET /auctions/1/edit
  def edit
    @auction = Auction.find(params[:id])
  end

  # POST /auctions
  # POST /auctions.xml
  def create
    @auction = Auction.new(params[:auction])

    respond_to do |format|
      if @auction.save
        format.html { redirect_to(admin_auction_path(@auction), :notice => 'Auction was successfully created.') }
        format.xml  { render :xml => @auction, :status => :created, :location => @auction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @auction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /auctions/1
  # PUT /auctions/1.xml
  def update
    @auction = Auction.find(params[:id])

    respond_to do |format|
      if @auction.update_attributes(params[:auction])
        format.html { redirect_to(admin_auction_path(@auction), :notice => 'Auction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @auction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.xml
  def destroy
    @auction = Auction.find(params[:id])
    @auction.destroy

    respond_to do |format|
      format.html { redirect_to(admin_auctions_url) }
      format.xml  { head :ok }
    end
  end

  # DELETE /admin/auctions/destroy_bid/1
  def destroy_bid
    @bid = Bid.find(params[:bid_id])
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to(:back || admin_auction_url(params[:auction_id])) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/auction/customer_auctions_controller.rb
class Auction::CustomerAuctionsController < ApplicationController
  before_filter  :current_time

  def categories
    @auctions = Auction.category_group
  end

  def list
    if params[:list_by_cheapest].blank?
        @auctions = Auction.list_by_time_left
    elsif params[:list_by_most_expensive].blank?
        @auctions = Auction.list_by_time_left
    elsif params[:list_by_name].blank?
        @auctions = Auction.list_by_time_left
    else
      @auctions = Auction.list_by_time_left
    end
    
  end

  def view
    @auction = Auction.find(params[:id])
  end

  private

  def current_time
    @time = Time.now
  end

end

app/controllers/auction/customer_bids_controller.rb
class Auction::CustomerBidsController < ApplicationController
  before_filter :require_user
  before_filter :get_user_and_auction, :only => [:new]

  def new
    @bid = @user.bids.build
    @bid.auction = @auction
    @bid.amount = @auction.current_bid    
  end

  def create
    @bid = Bid.new(params[:bid])
    if @bid.save
      redirect_to auctions_view_url(@bid.auction_id)
    else
      @auction = Auction.find(@bid.auction_id)
      @user = current_user
      @item = @auction.item
      render :action => :new
    end
  end

  def destroy
  end

  private

  def current_time
    @time = Time.now
  end

  def get_user_and_auction
    @user = current_user
    @auction = Auction.find(params[:auction_id])
    @item = @auction.item
  end

end

app/helpers/auction/customer_bids_helper.rb
module Auction::CustomerBidsHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/admin/auctions/_form.html.erb
<%= form_for([:admin, @auction]) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
        <% @auction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :item_id, "Item to Auction" %>
    <%= f.collection_select :item_id, Item.all, :id, :name, {:prompt => true}  %>
  </div>

  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time, {:discard_minute => true, :discard_second => true, :order => [:month, :day, :year], :start_year => Time.now.year} %> Hour
  </div>

  <% if f.object.new_record? %>
    <div class="field">
      <%= f.label :starting_amount, "Starting Bid Amount" %><br />
      $ <%= f.text_field :starting_amount, :size => 6 %> .00
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit :disable_with => "Please Wait..." %>
  </div>
<% end %>

app/views/admin/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_auction_path(@auction) %> |
<%= link_to 'Back', admin_auctions_path %>

app/views/admin/auctions/index.html.erb
<h1>Auctions Admin</h1>

<table>
  <tr>
    <th>Auction Item</th>
    <th>End time</th>
    <th>Top bidder</th>
    <th>Current bid</th>
  </tr>

<% @auctions.each do |auction| %>
  <tr>
    <%= render 'partials/auction_list', :locals => {:auction => auction} %>
    <td><%= link_to 'Show', admin_auction_path(auction) %></td>
    <td><%= link_to 'Edit', edit_admin_auction_path(auction) %></td>
    <td><%= link_to 'Destroy', admin_auction_path(auction), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Auction', new_admin_auction_path %>
---<%= link_to 'Admin Home', 'home/index' %>

app/views/admin/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_auctions_path %>

app/views/admin/auctions/show.html.erb
<%= render 'partials/auction' %>

<% if @auction.bids %>
  <h3>Bids on Auction:</h3>
  <table>
    <tr>
      <th>Item</th>
      <th>Bidder Account</th>
      <th>Time of Bid</th>
      <th>Bid Amount</th>
    </tr>
    <% @bids.each do |bid| %>
      <tr>
        <%= render 'partials/bid_list', :locals => {:bid => bid} %>
        <td><%= link_to "Bidder Info", admin_user_path(bid.user) %></td>
        <td><%= link_to "Delete", destroy_bid_admin_auction_path(:bid_id => bid.id, :auction_id => @auction.id), :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  <% else %>
    <h3>No Bids on this Auction Currently</h3>
  <% end %>
</table>

<%= link_to 'Edit Auction', edit_admin_auction_path(@auction) %> |
<%= link_to 'Admin Home', admin_auctions_path %>