config/routes.rb
CoinAuction::Application.routes.draw do |map|
  match "home" => 'home#index', :as => :home
  match "home/all_announcements" => 'home#all_announcements', :as => :all_announcements
  match "home/:id" => "home#announcement", :as => :announcement
  
  get "account/show"
  get "account/bids"
  get "account/history"
  match "logout" => 'user_sessions#destroy'
  resource :user_session, :only => [:destroy, :create, :new]

  scope :module => "auction" do
    match "auctions/categories" => 'customer_auctions#categories', :as => :auctions_categories
    match "auctions/list" => 'customer_auctions#list', :as => :auctions_list
    match "auctions/view/:id" => 'customer_auctions#view', :as => :auctions_view
    resource :customer_bid, :only => [:new, :create, :destroy]
  end

  
  namespace "admin" do
    get "home/index"
    resources :auctions do
      delete :destroy_bid, :on => :member
    end
    resources :items
    resources :announcements
    resources :users
  end

  

  root :to => 'home#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  scope :recent_first, order("created_at desc")
  scope :recent_10, recent_first.limit(5)

  validates_presence_of :title, :body
end

app/controllers/admin/announcements_controller.rb
class Admin::AnnouncementsController < ApplicationController
 # before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user

  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(admin_announcement_path(@announcement), :notice => 'Announcement was successfully created.') }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(admin_announcement_path(@announcement), :notice => 'Announcement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(admin_announcements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/admin/announcements/_form.html.erb
<%= form_for([:admin, @announcement]) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.cktext_area :body, :swf_params=>{:assetable_type=>'Demo', :assetable_id=>0} %>
  </div>
  <div class="actions">
    <%= f.submit :disable_with => "Please Wait..." %>
  </div>
<% end %>

app/views/admin/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_announcement_path(@announcement) %> |
<%= link_to 'Back', admin_announcements_path %>

app/views/admin/announcements/index.html.erb
<h1>Announcements Admin</h1>

<% @announcements.each do |announcement| %>
  <%= render 'partials/announcement_list', :locals => {:announcement => announcement} %>
  <p>
    <%= link_to 'Show', admin_announcement_path(announcement) %>---
    <%= link_to 'Edit', edit_admin_announcement_path(announcement) %>---
    <%= link_to 'Destroy', admin_announcement_path(announcement), :confirm => 'Are you sure?', :method => :delete %>
  </p>

<% end %>

<br />

<%= link_to 'New Announcement', new_admin_announcement_path %>
---<%= link_to 'Admin Home', 'home/index' %>

app/views/admin/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_announcements_path %>

app/views/admin/announcements/show.html.erb
<%= render 'partials/announcement'  %>


<%= link_to 'Edit', edit_admin_announcement_path(@announcement) %> |
<%= link_to 'Admin Home', admin_announcements_path %>