config/routes.rb
CoinAuction::Application.routes.draw do |map|
  match "home" => 'home#index', :as => :home
  match "home/all_announcements" => 'home#all_announcements', :as => :all_announcements
  match "home/:id" => "home#announcement", :as => :announcement
  
  get "account/show"
  get "account/bids"
  get "account/history"
  match "logout" => 'user_sessions#destroy'
  resource :user_session, :only => [:destroy, :create, :new]

  scope :module => "auction" do
    match "auctions/categories" => 'customer_auctions#categories', :as => :auctions_categories
    match "auctions/list" => 'customer_auctions#list', :as => :auctions_list
    match "auctions/view/:id" => 'customer_auctions#view', :as => :auctions_view
    resource :customer_bid, :only => [:new, :create, :destroy]
  end

  
  namespace "admin" do
    get "home/index"
    resources :auctions do
      delete :destroy_bid, :on => :member
    end
    resources :items
    resources :announcements
    resources :users
  end

  

  root :to => 'home#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  scope :recent_first, order("created_at desc")
  scope :recent_10, recent_first.limit(5)

  validates_presence_of :title, :body
end

app/models/auction.rb
include ActionView::Helpers::NumberHelper
class Auction < ActiveRecord::Base
  has_many :bids, :dependent => :destroy
  belongs_to :item

  validates_presence_of :starting_amount, :item_id, :end_time
  validates_numericality_of :starting_amount, :greater_than_or_equal_to => 0
  validates_presence_of :current_bid, :on => :update
  validates_numericality_of :current_bid, :on => :update
  
  after_create {|auction| auction.current_bid = auction.starting_amount if auction.current_bid.blank?}

  scope :category_group, joins(:item).order("item.series desc").includes(:item)
  scope :list_by_time_left, order("end_time desc").includes(:item)
  scope :list_by_cheapest, order("current_bid asc").includes(:item)
  scope :list_by_most_expensive, order("current_bid desc").includes(:item)
  scope :list_by_name, order("name desc").includes(:item)
  scope :list_by_popularity, joins(:bids).group('auctions.id').order("count(bids.id) desc").includes(:item)


  def current_bid_to_currency
    number_to_currency(self.current_bid)
  end

  def time_left_long
    t1 = Time.parse(self.end_time.to_s)
    t2 = Time.parse(Time.now.to_s)
    tl = t1 - t2
    if tl < 0
      return "Ended"
    end
    parse_time_left_long(tl)
  end

  def time_left_short
    t1 = Time.parse(self.end_time.to_s)
    t2 = Time.parse(Time.now.to_s)
    tl = t1 - t2
    if tl < 0
      return "Ended"
    end
    parse_time_left_short(tl)
  end


  def update_highest_bid
    if self.bids > 1
      max = self.bids.maximum("amount")
      max_bid = self.bids.where("amount == ?", max)
      self.update_attributes(:current_bid => max, :top_bidder => max_bid.first.user.login)
    else
      self.update_attributes(:current_bid => self.starting_amount, :top_bidder => "")
    end
  end


  
  private

  

  def parse_time_left_long(time)
    s=""
    seconds = (time%(60)).to_i
    minutes = ((time%(60*60))/60).to_i
    hours = (time%(60*60*24)/(60*60)).to_i
    days = (time/(60*60*24)).to_i
    s << "#{days} day#{'s' if days > 1}, " if days > 0
    s << "#{hours} hr#{'s' if hours > 1}, " if hours > 0
    s << "#{minutes} min#{'s' if minutes > 1}, " if minutes > 0
    s << "#{seconds} sec" if seconds > 0
    return s
  end

  def parse_time_left_short(time)
    s="Error"
    seconds = (time%(60)).to_i
    minutes = ((time%(60*60))/60).to_i
    hours = (time%(60*60*24)/(60*60)).to_i
    days = (time/(60*60*24)).to_i
    if days > 0
      s = "#{days} day#{'s' if days > 1}, " if days > 0
      s << "#{hours} hr#{'s' if hours > 1}" if hours > 0
    else
      s = "#{hours} hr#{'s' if hours > 1}, " if hours > 0
      s << "#{minutes} min#{'s' if minutes > 1}, " if minutes > 0
      s << "#{seconds} sec" if seconds > 0
    end
    return s
  end
end


#  def time_left_long(end_datetime, current_datetime=Time.now)
#    t1 = Time.parse(end_datetime.to_s)
#    t2 = Time.parse(current_datetime.to_s)
#    tl = t1 - t2
#    if tl < 0
#      return "Ended"
#    end
#    parse_time_left_long(tl)
#  end

app/models/bid.rb
include ActionView::Helpers::NumberHelper
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction

  validates_associated :user, :auction
  validates_presence_of :amount
  validate :amount_greater_than_zero
  validate :update_auction_bid

  after_destroy :update_auction_high_bid

  
  def amount_to_currency
    number_to_currency(self.amount)
  end

  protected

  def update_auction_high_bid
    if self.auction
      self.auction.update_highest_bid
    end
  end
  
  def amount_greater_than_zero
    errors.add(:amount, "should be at least 0.01") if amount.nil? || amount < 0.01
  end

  def update_auction_bid
    unless self.amount > self.auction.current_bid and self.auction.update_attributes(:current_bid => self.amount, :top_bidder => self.user.login)
      errors.add(:amount, "needs to be greater than the current bid of #{self.auction.current_bid_to_currency}.")
    end
  end

end

app/models/coin.rb
class Coin < Item
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :product, :polymorphic => true
  has_many :auctions, :dependent => :destroy

  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    #    c.my_config_option = my_value # for available options see documentation in: Authlogic::ActsAsAuthentic
  end # block optional
  has_many :bids

  validates_presence_of :login
  validates_uniqueness_of :login

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  def show
  end

  def bids
  end

  def history
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  helper :all
  helper_method :current_user_session, :current_user
  before_filter :side_panels
  #filter_parameter_logging :password, :password_confirmation DEPRICATED

  private

  def side_panels
    @popular_auctions = Auction.all #list_by_popularity.limit(5)
    @time = Time.now
    if current_user
      @user = current_user
    else
      @user_session = UserSession.new
    end
  end  
  
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end

  def require_user
    unless current_user
      store_location
      flash[:important_notice] = "You must be logged in to access this page"
      redirect_to new_user_session_url
      return false
    end
  end

  def require_no_user
    if current_user
      store_location
      flash[:important_notice] = "You must be logged out to access this page"
      redirect_to account_url
      return false
    end
  end

  def store_location
    session[:return_to] = request.request_uri
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @announcements = Announcement.recent_10
  end

  def announcement
    @announcement = Announcement.find(params[:id])
  end

  def all_announcements
    @announcements = Announcement.recent_first
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default home_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default home_url
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  

  def to_currency(decimal)
    number_to_currency(decimal)
  end

  
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/customer_auctions_helper.rb
module CustomerAuctionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin.html.erb
<h3>Admin Tools</h3>
<ul>
  <li><%= link_to "Announcements Admin", admin_announcements_path %></li>
  <li><%= link_to "Auctions Admin", admin_auctions_path %></li>
  <li><%= link_to "Items Admin", admin_items_path %></li>
  <li><%= link_to "Users Admin", admin_users_path %></li>
</ul>

app/views/layouts/_auctions.html.erb
<h3>Popular Auctions (Time: <%= @time %>)</h3>
<table class="panel">
  <tr>
    <th>Item</th>
    <th>Auction End Time</th>
    <th>Current Bid</th>
  </tr>
  <% @popular_auctions.each do |auction| %>
  <tr onclick="location.href='<%= auctions_view_url(auction.id) %>';" style="cursor: pointer;" onmouseover="this.className='hover';" onmouseout="this.className='';" >
    <%= render 'partials/auction_list', :locals => {:auction => auction}%>
  </tr>
<% end %>
</table>

app/views/layouts/_login.html.erb
<h3>Login</h3>

<%= form_for @user_session, :url => user_session_path do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited your user from being saved:</h2>

      <ul>
        <% @user_session.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.check_box :remember_me %><%= f.label :remember_me %>
  </div>

  <div class="action">
    <%= f.submit "Login",  :disable_with => "Please Wait..." %>
  </div>
<% end %>

<%= link_to "Register", new_admin_user_path %>

app/views/layouts/_logout.html.erb
<p>
  <strong>Logged in as:</strong><br/>
  <%= @user.login %>
</p>
<%= button_to 'Logout', logout_url, :method => :post, :disable_with => "Please Wait..." %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinAuction</title>
    <%= stylesheet_link_tag "scaffold" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag :ckeditor %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="right-panel">
      <div class="panel"><%= render "layouts/auctions" %></div>
      <div class="panel"><%= render 'layouts/admin' %></div>
      <% unless @user %>
        <div class="panel"><%= render 'layouts/login' %></div>
      <% else %>
        <div class="panel"><%= render 'layouts/logout'%></div>
      <% end %>
    </div>

    <% if flash[:notice] %> <p id="notice"><%= notice %></p> <% end %>
    <% if flash[:important_notice] %> <p id="important-notice"><%= flash[:important_notice] %></p><% end %>

    <%= yield %>

  </body>
</html>

app/views/partials/_announcement.html.erb
<% announcement = defined?(locals[:announcement]) ? locals[:announcement] : @announcement %>

<h3><%= announcement.title %></h3>

<p><%=raw announcement.body %></p>

app/views/partials/_announcement_list.html.erb
<% announcement = defined?(locals[:announcement]) ? locals[:announcement] : @announcement %>

<td><%= announcement.title %></td>

app/views/partials/_auction.html.erb
<% auction = defined?(locals[:auction]) ? locals[:auction] : @auction %>

<% if auction.item %>
  <h3>Auction Item: </h3>
  <%= render 'partials/item', :locals => {:item => auction.item} %>
<% else %>
  <h2>No Item Associated</h2>
<% end %>

<h3>Auction Details: </h3>
<p>
  <strong>Time Left:</strong>
  <%= auction.time_left_long %>
</p>

<p>
  <strong>Top bidder:</strong>
  <%= auction.top_bidder %>
</p>

<p>
  <strong>Current bid:</strong>
  <%= auction.current_bid_to_currency %>
</p>

app/views/partials/_auction_list.html.erb
<% auction = defined?(locals[:auction]) ? locals[:auction] : @auction %>

<td>
  <% if auction.item %>
    <strong><%= auction.item.name %><%= (" (" + auction.item.age.year.to_s + ")") if auction.item.age %></strong>
  <% else %>
    <strong>Item Error!</strong>
  <% end %>
</td>

<td>
  <%= auction.time_left_short %>
</td>

<td>
  <%= auction.current_bid_to_currency %>
</td>

app/views/partials/_bid.html.erb
<% bid = defined?(locals[:bid]) ? locals[:bid] : @bid %>  

<h3>Bid For:</h3>
<% if bid.auction and bid.auction.item %>
  <p><%= render 'item', :locals => {:item => bid.auction.item} %></p>
  <p><strong>Time Left:</strong> <%= time_left(bid.auction.end_time) %></p>
<% else %>
  <p><strong>Error!</strong> No Item Associated</p>
<% end %>


<p>
  <strong>Bidder: </strong>
  <%= bid.user.login if bid.user || "Error! No User Associated" %>
</p>

<p>
  <strong>Time of Bid: </strong>
  <%= bid.created_at %>
</p>

<p>
  <strong>Bid Amount: </strong>
  <%= bid.amount_to_currency %>
</p>

app/views/partials/_bid_list.html.erb
<% bid = defined?(locals[:bid]) ? locals[:bid] : @bid %>

<td>
  <% if bid.auction and bid.auction.item %>
    <strong><%= bid.auction.item.name %><%= (" (" + bid.auction.item.age.year.to_s + ")") if bid.auction.item.age %></strong>
  <% else %>
    <strong>Error!</strong> No Item Associated
  <% end %>
</td>

<td>
  <%=  bid.user ? bid.user.login : "Error! No User Associated" %>
</td>

<td>
  <%= bid.created_at %>
</td>

<td>
  <%= bid.amount_to_currency %>
</td>

app/views/partials/_item.html.erb
<% item = defined?(locals[:item]) ? locals[:item] : @item %>

<h3><%= item.name %></h3>
<p>
  <strong>Age: </strong>
  <%= item.age %>
</p>

<p>
  <strong>Series: </strong>
  <%= item.series %>
</p>

<p>
  <strong>Diameter: </strong>
  <%= item.diameter %>
</p>

<p>
  <strong>Designer: </strong>
  <%= item.designer %>
</p>

<p>
  <strong>Weight: </strong>
  <%= item.weight %>
</p>

<p>
  <strong>Edge: </strong>
  <%= item.edge %>
</p>

<p>
  <strong>Metal content: </strong>
  <%= item.metal_content %>
</p>

app/views/partials/_item_list.html.erb
<% item = defined?(locals[:item]) ? locals[:item] : @item %>

<td><strong><%= item.name %></strong></td>

<td>
  <%= item.age %>
</td>

<td>
  <%= item.series %>
</td>

app/views/partials/_user.html.erb
<% user = defined?(locals[:user]) ? locals[:user] : @user %>

<h3>
  <%= user.login %>
</h3>

<p>
  <strong>Login Count: </strong>
  <%= user.login_count %>
</p>

<p>
  <strong>Last Login At:</strong>
  <%= user.last_login_at %>
</p>

app/views/partials/_user_list.html.erb
<% user = defined?(locals[:user]) ? locals[:user] : @user %>

<td>
  <%= user.login %>
</td>

<td>
  <%= user.login_count %>
</td>

<td>
  <%= user.last_login_at %>
</td>